package com.alejandro.randomplots.data
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "images")
data class ImageEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val uri: String, // Path to the image file
    val name: String, // Optional: User-provided name or autogenerated
    val timestamp: Long // When the image was created
)
